packageName: hindsight_client_api
projectName: hindsight-client
packageVersion: 0.0.7
library: asyncio
generateSourceCodeOnly: true
# Don't generate auto tests or docs - we have our own
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
