apiVersion: v2
name: hindsight
description: Hindsight helm chart
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - ai
  - memory
  - llm
  - agents
maintainers:
  - name: Hindsight Team
