generatorName: go
outputDir: ./
inputSpec: ../../hindsight-docs/static/openapi.json
packageName: hindsight
gitUserId: vectorize-io
gitRepoId: hindsight/hindsight-clients/go
isGoSubmodule: true
enumClassPrefix: true
structPrefix: true
generateInterfaces: true
